<?php

namespace App\Http\Requests\Account;

use Illuminate\Foundation\Http\FormRequest;

class FormProfileRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(): array
    {
        return [
            'name'      => ['min:2', 'string'],
            'email'     => ['email'],
            'tel'       => ['sometimes'],
            'telegram'  => ['sometimes'],
        ];
    }

    public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes(): array
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }
}
